# Generated by Django 2.0 on 2018-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(default=True, null=True, upload_to='fotos_perfiles'),
        ),
    ]
