# Generated by Django 2.0 on 2018-04-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='profile_picture',
            new_name='foto_perfil',
        ),
    ]
