# Generated by Django 2.0 on 2018-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180419_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default=True, null=True, upload_to='foto_perfiles'),
        ),
    ]
