# Generated by Django 2.0.3 on 2018-05-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_tarjeta_tipo_divisa'),
        ('usuario', '0004_auto_20180419_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Tarjeta'),
        ),
    ]
