# Generated by Django 2.0.3 on 2018-05-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tarjeta',
        ),
    ]
