# Generated by Django 2.0.3 on 2018-05-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('csc', models.IntegerField()),
                ('fecha_vencimiento_mm', models.IntegerField()),
                ('fecha_vencimiento_aa', models.IntegerField()),
                ('tipo_divisa', models.CharField(max_length=5)),
            ],
        ),
    ]
