# Generated by Django 2.0.3 on 2018-05-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='tipo_divisa',
        ),
    ]
