# Generated by Django 2.0.3 on 2018-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_tarjeta_tipo_divisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='tipo_divisa',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
