# Generated by Django 2.0.3 on 2018-05-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_tarjeta'),
        ('gestion', '0003_tarjeta_tipo_divisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
