# Generated by Django 2.0.3 on 2018-05-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_tarjeta_id_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='id_persona',
            new_name='persona',
        ),
    ]
