# Generated by Django 2.0.3 on 2018-05-18 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0005_auto_20180518_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='persona',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
