# Generated by Django 2.0.3 on 2018-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='csc',
            new_name='numero_cuenta',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='entidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
