# Generated by Django 2.0.3 on 2018-05-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20180521_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.BigIntegerField(),
        ),
    ]
