# Generated by Django 2.0.3 on 2018-05-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20180521_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='entidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
