# Generated by Django 2.0.3 on 2018-05-21 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0012_auto_20180521_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('entidad', models.CharField(max_length=50)),
                ('numero_cuenta', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('interes', models.IntegerField()),
                ('fecha_prestamo', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('tipo_divisa', models.CharField(max_length=5, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
