# Generated by Django 2.0.3 on 2018-05-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_tarjeta_saldo_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chequera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('entidad', models.CharField(max_length=50)),
                ('tipo_divisa', models.CharField(max_length=5)),
                ('numero_cuenta', models.IntegerField()),
                ('monto', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='inversion',
            name='monto',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.BigIntegerField(),
        ),
    ]
