# Generated by Django 2.0.3 on 2018-05-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_chequera_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequera',
            name='numero_cheques',
            field=models.IntegerField(null=True),
        ),
    ]
