# Generated by Django 2.0.3 on 2018-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='periodo_recurrencia',
            field=models.CharField(max_length=50),
        ),
    ]
