# Generated by Django 2.0.3 on 2018-05-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_auto_20180524_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='tipo_divisa',
        ),
    ]
