# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_auto_20180524_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequera',
            name='tipo',
            field=models.CharField(default='chequera', max_length=50),
        ),
        migrations.AddField(
            model_name='inversion',
            name='tipo',
            field=models.CharField(default='inversion', max_length=50),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.CharField(default='prestamos', max_length=50),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(default='tarjeta', max_length=50),
        ),
    ]
