# Generated by Django 2.0.3 on 2018-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_auto_20180525_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequera',
            name='monto',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='interes',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='monto',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='interes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='monto',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='saldo_inicial',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='monto',
            field=models.BigIntegerField(null=True),
        ),
    ]
