# Generated by Django 2.0.3 on 2018-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_auto_20180525_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(default='gasto', max_length=50),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo',
            field=models.CharField(default='ingreso', max_length=50),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(default='transferencia', max_length=50),
        ),
    ]
