# Generated by Django 2.0.3 on 2018-05-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_auto_20180525_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequera',
            name='numero_cuenta',
            field=models.BigIntegerField(null=True),
        ),
    ]
