# Generated by Django 2.0.3 on 2018-05-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_auto_20180525_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='tipo',
        ),
    ]
